name: dartdocgenerator
version: 0.0.1

description: Generates Codacy linter documentation

patternsSdkVersion: 2.15.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  linter: 1.18.0
  yaml: ^3.0.0