FROM dart:2.15.1

RUN apt-get update && apt-get install -y openjdk-11-jre

COPY docs /docs
COPY target/universal/stage/ /workdir/
RUN chmod 755 /usr/lib/dart && chmod +x /workdir/bin/codacy-dartanalyzer
RUN adduser --uid 2004 --disabled-password --gecos "" docker
USER docker
WORKDIR /src
ENTRYPOINT ["/workdir/bin/codacy-dartanalyzer"]
