FROM norionomura/swiftlint:0.43.1_swift-5.4.0 as builder

FROM swift:5.5.0-xenial-slim

RUN apt-get update && apt-get install -y openjdk-8-jre

COPY --from=builder /usr/bin/swiftlint /usr/bin/swiftlint
COPY --from=builder /usr/lib/libsourcekitdInProc.so /usr/lib/libsourcekitdInProc.so

COPY docs /docs
COPY target/universal/stage/ /workdir/
RUN chmod +x /workdir/bin/codacy-swiftlint
RUN adduser --uid 2004 --disabled-password --gecos "" docker
USER docker
WORKDIR /src
ENTRYPOINT ["/workdir/bin/codacy-swiftlint"]
