version: 2.1

orbs:
  codacy: codacy/base@6.1.3
  codacy_plugins_test: codacy/plugins-test@1.1.1

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt scalafmtCheckAll graalvm-native-image:packageBin
            docker buildx create --use
            docker buildx build -o type=docker,dest=- --platform linux/arm64/v8,linux/amd64 --build-arg TOOL_VERSION=$(cat .tool_version) -t $CIRCLE_PROJECT_REPONAME:latest . > docker-image.tar
          persist_to_workspace: true
          cache_prefix: sbt-cache-18032022-3
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
