version: 2.1

orbs:
  codacy: codacy/base@4.2.7
  codacy_plugins_test: codacy/plugins-test@0.14.5

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 graalvm-native-image:packageBin"
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            # Install Ammonite
            sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.3.8/2.13-2.3.8) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'
            # Run doc-generator
            sudo amm doc-generator.sc
            # Update docker image with generated docs
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
